### ISSUE TITLE
memory source state indexing is broken

### ISSUE THREAD

**Issue by flucivja** [reach/router#279]
When called createMemorySource the location stack is initialised with 1st entry but states stack is empty array. Therefor when push state is called via navigate on history with some state then 2nd entry is added to location stack, state is inserted as the first entry to state stack and index is incremented. Then when asking for the state, the undefined is returned because index is already 1 but there is only 1 item in state stack.

Solution would be to init state stack with the empty object as first entry.

https://github.com/reach/router/blob/4cd2e31297f2293ba701a6f1146fb55a29a26c26/src/lib/history.js#L72

Note:
I did workaround by calling createMemorySource and then immediately calling source.history.replaceState which adds initial entry to state stack.

**Comment by mtliendo** [comment]
This has been fixed in latest master branch by initializing `states` to `null`

https://github.com/reach/router/blob/master/src/lib/history.js#L82

**Comment by Xapphire13** [comment]
@mtliendo, this is still broken in the currently publish version of reach-router (v1.2.1). See https://github.com/reach/router/blob/ceb4e8762e7432c9f5a940cb811698aabfc4d564/src/lib/history.js#L72 (the commit is from the time v1.2.1 was cut).

Should this be re-opened until the fix is pushed?
