### ISSUE TITLE
Passing state option in navigate doesn't seem to work

### ISSUE THREAD

**Issue by websymphony** [reach/router#96]
When `state` option is provided to `navigate`, it is not available in the `props.location.state` object for the matched components.

Example sandbox: https://codesandbox.io/s/l27754822m

Steps to reproduce:
* Click on 'Invoices' link.
* Add some ID in the input field.
* Click on 'create' button.
* Watch console which is logging `props.location.state` for `Invoice` and `Invoices` components.

I have taken the example from documentation and updated the `Invoices` component to have `state` option { invoiceID: provided_id } for the `navigate` function. 
`props.location.state` seems to only have `key` and no other information for the matched `Invoice` and `Invoices` components. 

Is it a bug or am I not using the option correctly? 😕

**Comment by milamer** [comment]
I think the documentation is wrong.
You can add a state by providing navigate with an options object with a `state` property, the data under the `state` property will then be merged with the key.

This means your code should look like this:
```
<form
      onSubmit={event => {
        event.preventDefault();
        const id = event.target.elements[0].value;
        event.target.reset();

        // Adding state option along with navigation.
        navigate(`/invoices/${id}`, { state: {invoiceID: id }});
      }}
    >
```

I replaced 
```
navigate(`/invoices/${id}`, { invoiceID: id });
```
with
```
navigate(`/invoices/${id}`, { state: {invoiceID: id }});
```

Hope that helps

**Comment by websymphony** [comment]
Awesome, yes that was it. Many thanks!

**Comment by akoolenbourke** [comment]
This needs to be opened as a defect because the docs are just plain wrong - still. I spent hours trying to work this out only to eventually find this post that fixed it in an instant.

**Comment by websymphony** [comment]
The documentation was fixed via: https://github.com/reach/router/pull/80

Problem is that the new documentation hasn't been deployed yet. We can keep this issue open until the documentation is updated.

**Comment by akoolenbourke** [comment]
May I suggest docs fixes be deployed regularly. It's not like they need rigorous testing and it would really help.

I would also like better docs in general. As I'm quite new to react et al I found that the docs just assumed I knew a lot more than I did, without really pointing me to where to learn more. I had a nightmare trying to figure out why props.location didn't exist in one of my components until I found <Location> and I had to put that somewhere up the hierarchy to get props.location. Was a pain to be honest because some components have props.location and some don't and I really don't know why it is this way.

Note, I'm using Gatsby which uses @reach-router.

**Comment by rubenbase** [comment]
Please update the docs.

**Comment by postcasio** [comment]
I had this issue today. The documentation is still incorrect.

**Comment by trip16661** [comment]
Can confirm the docs are still incorrect.

https://reach.tech/router/api/navigate option  section.

**Comment by b-tiwari** [comment]
please correct the wrong documentation, it costed me a day 
https://reach.tech/router/api/navigate

**Comment by teseo** [comment]
The documentation is still incorrect

**Comment by iifeoluwa** [comment]
Can confirm that I also lost some time to this today, kindly help fix this for others.

**Comment by mtliendo** [comment]
🎉[docs have been updated](https://reach.tech/router/api/navigate) to reflect the proper way to pass state into navigate. 🎉

**Comment by Phyros64** [comment]
I'm afraid the issue is still there:
https://reach.tech/router/api/navigate
```navigate("/todos", { newId: id })```

**Comment by jacekk** [comment]
@mtliendo @ryanflorence This issue has been fixed over a year ago in https://github.com/reach/router/commit/e8325ae7a2d7be0a4e1de266ee15929f85fc2d94 - but still confuses people. May I ask why?

**Comment by RifRaf44** [comment]
@mtliendo I'm afraid I ran into this issue today, luckily I stumbled on this link pretty quickly but the documentation is still showing the wrong syntax.

**Comment by mnishiguchi** [comment]
@ryanflorence I checked the document's source to see if I can contribute. It is already fixed in the source markdown. I may just have not been published yet for some reason.
https://github.com/reach/router/blob/master/website/src/markdown/api/navigate.md#option---state

**Comment by hassib-ashouri** [comment]
I think we should open another issue. docs are still wrong

**Comment by jamie29w** [comment]
Can you please re-open. The docs are still incorrect. Similar to @RifRaf44, I'm glad I found this issue.

![Screen Shot 2020-02-13 at 2 17 36 PM](https://user-images.githubusercontent.com/30516128/74483602-a1b9d880-4e6b-11ea-8064-3ed3a25a3dba.png)

**Comment by jacekk** [comment]
@blainekasten , as the most active in this repo since the beginning of this year, can you take a look at this issue?

**Comment by blainekasten** [comment]
I'm pinging Ryan for this. I don't have website admin. I'll try to get this fixed

**Comment by blainekasten** [comment]
The docs have been updated! Sorry for the delay everone!

**Comment by odalysadam** [comment]
Hi!
So I'm doing this `props.navigate('code', { state: { test: confirmationResult } })` and it navigates correctly, but state is null. Anyone any idea why?

**Comment by jacekk** [comment]
@odalysadam How do you "read" the state? An example code snippet would be helpful to answer.

**Comment by odalysadam** [comment]
@jacekk Of course, sorry. Currently just logging `location` out of props in the route component for `/code`. It shows the correct pathname as well, but it looks as though the whole app gets reloaded. ( app as in base path for my client side routes)

**Comment by jacekk** [comment]
@odalysadam I dunno why the whole app might gets **realoded** when using `navigate`, but please bear in mind that `naviate('code')` is a relative route. Maybe try `/code`... or maybe even just a slash `/`. Those are absolute routes - starting with a slash. Relative routes might be sometimes troublesome, especially when `basePath` is not the top-level one.

Just guessing though, as I've never had a problem with missing `state` while using `navigate` :/

**Comment by odalysadam** [comment]
@jacekk Thanks, I'll try an absolute path and see if the full reload still happens.

**Comment by odalysadam** [comment]
@jacekk Using an absolute path changed nothing, but state is most likely null because on reload everything gets lost. 

Is triggering a full reload something that navigate even does or should I be looking elsewhere for the problem?

**Comment by jacekk** [comment]
@odalysadam It works for me --> [![Edit brave-turing-dtkcn](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/brave-turing-dtkcn?fontsize=14&hidenavigation=1&theme=dark)

Can you replicate? Or share your project/code? Simple `props.navigate('/code', { state: { test: 'confirmationResult' } });` should be working correctly.

**Comment by odalysadam** [comment]
@jacekk Ok, then the problem lies elsewhere. Thank you very much!

**Comment by HenryKenya** [comment]
I can see the state, but it only has key...nothing more
`navigate("/auth", { test: "test"})`

![Screenshot 2020-10-12 at 12 14 34 (2)](https://user-images.githubusercontent.com/24941233/95728782-95994b80-0c84-11eb-887e-3ff7a4f0ae6d.png)

**Comment by jacekk** [comment]
> I can see the state, but it only has key...nothing more
> `navigate("/auth", { test: "test"})`

@HenryKenya Try this:
```js
navigate("/auth", { state: { fooKey: "fooValue" }});
```

**Comment by HenryKenya** [comment]
@jacekk done that. Still having the same issue of seeing only keys

> > I can see the state, but it only has key...nothing more
> > `navigate("/auth", { test: "test"})`
> 
> @HenryKenya Try this:
> 
> ```js
> navigate("/auth", { state: { fooKey: "fooValue" }});
> ```

**Comment by jacekk** [comment]
@HenryKenya Then try to replicate in some other component or in a separate project. This definitely works:
[![Edit brave-turing-dtkcn](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/brave-turing-dtkcn?fontsize=14&hidenavigation=1&theme=dark)

**Comment by HenryKenya** [comment]
@jacekk checked out the sandbox. It has the same issue of just showing keys and no value

**Comment by HenryKenya** [comment]
![Screenshot 2020-10-12 at 12 27 51 (2)](https://user-images.githubusercontent.com/24941233/95730075-6d125100-0c86-11eb-9f97-9632a81029c4.png)
I think it's a bug. cc @ryanflorence

**Comment by HenryKenya** [comment]
@jacekk checked it out again. The issue must be somewhere else. Let me try debug it

**Comment by HenryKenya** [comment]
could the issue be that I am trying to access state using the `useLocation` hook?

**Comment by jacekk** [comment]
>  checked out the sandbox. It has the same issue of just showing keys and no value

@HenryKenya 
You saaay WUT? Please, just point out what is NOT working here:
![image](https://user-images.githubusercontent.com/1695878/95730506-a21aa580-0c7e-11eb-93e4-489d44eafdf1.png)

**Comment by HenryKenya** [comment]
> > checked out the sandbox. It has the same issue of just showing keys and no value
> 
> @HenryKenya
> You saaay WUT? Please, just point out what is NOT working here:
> ![image](https://user-images.githubusercontent.com/1695878/95730506-a21aa580-0c7e-11eb-93e4-489d44eafdf1.png)

The sandbox works..confirmed 😂
Still not sure what it is I have done wrong. Are props the only way to access the same or can someone use `useLocation` hook too?

**Comment by jacekk** [comment]
This line --> https://github.com/reach/router/blob/master/src/index.js#L69 get location from history prop, but the following line does not pass it --> https://github.com/reach/router/blob/master/src/index.js#L43

@HenryKenya
I guess you've found a bug, but it is not related to this very ticket :smile: Please, report a separate one.
